#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jackson-dataformat-smile
Version  : 2.6.6
Release  : 1
URL      : https://github.com/FasterXML/jackson-dataformat-smile/archive/jackson-dataformat-smile-2.6.6.tar.gz
Source0  : https://github.com/FasterXML/jackson-dataformat-smile/archive/jackson-dataformat-smile-2.6.6.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6/jackson-dataformat-smile-2.6.6.jar
Source2  : https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6/jackson-dataformat-smile-2.6.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jackson-dataformat-smile-data = %{version}-%{release}
Requires: mvn-jackson-dataformat-smile-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
## Overview
This Jackson extension handles reading and writing of data encoded in [Smile](http://wiki.fasterxml.com/SmileFormatSpec) data format ("binary JSON").
It extends standard Jackson streaming API (`JsonFactory`, `JsonParser`, `JsonGenerator`), and as such works seamlessly with all the higher level data abstractions (data binding, tree model, and pluggable extensions).

%package data
Summary: data components for the mvn-jackson-dataformat-smile package.
Group: Data

%description data
data components for the mvn-jackson-dataformat-smile package.


%package license
Summary: license components for the mvn-jackson-dataformat-smile package.
Group: Default

%description license
license components for the mvn-jackson-dataformat-smile package.


%prep
%setup -q -n jackson-dataformat-smile-jackson-dataformat-smile-2.6.6

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jackson-dataformat-smile
cp src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-jackson-dataformat-smile/src_main_resources_META-INF_LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6/jackson-dataformat-smile-2.6.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6/jackson-dataformat-smile-2.6.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6/jackson-dataformat-smile-2.6.6.jar
/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.6/jackson-dataformat-smile-2.6.6.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jackson-dataformat-smile/src_main_resources_META-INF_LICENSE
